# Generated by Django 4.1.1 on 2023-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
