version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_DB: ${DB_NAME:-graphqldb}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - graphqldb:/var/lib/postgresql/data
  graphql_bookstore:
    build: .
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: ${SECRET_KEY:-secret}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME:-a}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-t}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-i}
      AWS_REGION_NAME: ${AWS_REGION_NAME:-j}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_HOST: 'db'
      DB_NAME: ${DB_NAME:-graphqldb}
    command: bash -c "/app/entrypoint.sh"
    volumes:
      - ./:/app/
    depends_on:
      - db
    links:
      - db:db
volumes:
  graphqldb:

