# Generated by Django 4.1.1 on 2023-01-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderBook',
        ),
    ]
