# Generated by Django 4.1.1 on 2023-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_book_image_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies_sold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
