# Generated by Django 4.1.1 on 2023-01-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_alter_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
