# Generated by Django 4.1.1 on 2023-02-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0011_alter_book_copies_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_sold',
            field=models.IntegerField(default=0),
        ),
    ]
