# Generated by Django 4.1.1 on 2023-02-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_alter_book_copies_sold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
