# Generated by Django 4.1.1 on 2023-02-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_address_order_delivered_order_in_transit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_book',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_book', to='Orders.order'),
        ),
    ]
